meta_product_name: "Artket"
meta_title: "Artket - la plateforme des galeries d'art"
meta_description: "Découvrez sur Artket, la première plateforme africaine d'Art, 10 000 Oeuvres d'Art des grands artistes d'aujourd'hui et de demain"
meta_image: "cover.jpg"                       # should exist in `app/assets/images/`